PCI: imx6: Fix compile error
Fixes:

	drivers/pci/host/pci-imx6.c:1341:10: error: 'pci_imx_pm_ops' undeclared here (not in a function)
	   .pm = &pci_imx_pm_ops,
		  ^
	make[3]: *** [drivers/pci/host/pci-imx6.o] Error 1
	make[2]: *** [drivers/pci/host] Error 2

introduced in:

	commit 09c9222c2563a37a3ec2e5f68c06d5432f44db1e
	Author: Richard Zhu <r65037@freescale.com>
	Date:   Fri Sep 26 16:53:31 2014 +0800

	    MLK-10009-8 PCI: imx6: Add imx6sx pcie support

Signed-off-by: Petr Štetiar <ynezz@true.cz>