serial: ar933x_uart: Fix build failure with disabled console
Andrey has reported on OpenWrt's bug tracking system[1], that he's
currently not possible to use ar93xx_uart as pure serial UART without
console (CONFIG_SERIAL_8250_CONSOLE and CONFIG_SERIAL_AR933X_CONSOLE
undefined), because compilation ends with following error:

 ar933x_uart.c: In function 'ar933x_uart_console_write':
 ar933x_uart.c:550:14: error: 'struct uart_port' has no member named 'sysrq'

So this patch moves all the code related to console handling behind
series of CONFIG_SERIAL_AR933X_CONSOLE ifdefs.

1. https://bugs.openwrt.org/index.php?do=details&task_id=2152

Tested-by: Andrey Batyiev <email@missing.fixme>
Reported-by: Andrey Batyiev <email@missing.fixme>
Signed-off-by: Petr Štetiar <ynezz@true.cz>